name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test build output
        run: |
          if [ -d "dist" ]; then
            echo "Build successful! dist directory exists."
            ls -la dist
          else
            echo "Build failed! dist directory does not exist."
            exit 1
          fi